name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira Action"
        run: echo "Hello World"
      - name: "Segunda Action"
        run: |
          echo "Primeiro Comando"
          echo "Segundo Comando"
  segundo-job:
    name: "Job com Action de NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação versão NodeJS atual"
        run: node --version
    
          
