# Análisa o código com SonarCloud
# Faz o Build da imagem
# Analisa a imagem com Trivy
# Faz push para o DockerHub
name: Ci 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar_repo
        uses: actions/checkout@v3
        with:
          repository: Adenilson365/estudosgit
          token: ${{ secrets.ACCESS_TOKEN_GIT}}
          path:  . 

      - name: Atualizar tag 
        run: |
          pwd
          ls -a 
          sed -i 's|image: adenilsonkon/devopslabs-api-images:.*|image: adenilsonkon/devopslabs-api-images:15456465|' ./application/deployments/deployment.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GIT}}
      - name: Commit e Push
        run: |
          pwd
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update docker tag para:  132132"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_GIT}}
