# Análisa o código com SonarCloud
# Faz o Build da imagem
# Analisa a imagem com Trivy
# Faz push para o DockerHub
name: Ci 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Mostrar contexto do GitHub
      #   run: echo '${{ toJson(github) }}'
      # - name: split
      #   run: |
      #       sha="${GITHUB_SHA}"
      #       final="${sha:0:7}"
      #       echo "$final"
      - name: teste
        run: |
             echo "SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
             echo "$GITHUB_ENV"
        
      - name: print
        run: echo "$GITHUB_ENV"
