name: push
on:
  push:
env:
  ambiente: prod
jobs:
    tf_plan:
      uses: Adenilson365/aprendendo-github-actions/.github/workflows/ci.yml@main
      secrets: inherit
    tf_push:
      runs-on: ubuntu-latest
      steps:
        - name: Debug de push
          run: | 
            echo "${{ env.ambiente }}"