name: push
on:
  push:
jobs:
    tf_plan:
      uses: Adenilson365/aprendendo-github-actions/.github/workflows/ci.yml@main
      secrets: inherit
      with:
        ENV: "teste"

    tf_push:
      runs-on: ubuntu-latest
      steps:
        - name: Debug de push
          run: | 
            