name: push
on:
  push:
jobs:

    tf_push:
      runs-on: ubuntu-latest
      steps:
        - name: Debug de push
          run: | 
            echo "${{ github.base_ref == 'main' && 'prod' || (github.base_ref == 'dev' && 'dev' || 'feat') }}"
            echo "Basename: ${{ github.base_ref }}"
            echo "refname: ${{ github.ref_name }}"

            echo "eventName: ${{ github.event_name }}"